---
title: "Nominal house prices data in Luxembourg - Analysis"
author: "Jake Tufts"
date: "`r Sys.Date()`"
---

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
```


Load the datasets

```{r}
commune_level_data <- read.csv("datasets/house_prices_commune_level_data.csv")
country_level_data <- read.csv("datasets/house_prices_country_level_data.csv")
```


Compute the Laspeyeres index:

```{r}
get_laspeyeres_index <- function(dataset, start_year = "2010"){
  
  which_dataset <- deparse(substitute(dataset))
  
  group_var <- if(grepl("commune", which_dataset)){
               quo(locality)
             } else {
               NULL
             }
  dataset  %>% 
    group_by(!!group_var) %>% 
    mutate(p0 = ifelse(year == start_year, average_price_nominal_euros, NA)) %>%
    fill(p0, .direction = "down") %>%
    mutate(p0_m2 = ifelse(year == start_year, average_price_m2_nominal_euros, 
  NA)) %>%
    fill(p0_m2, .direction = "down") %>%
    ungroup() %>%
    mutate(pl = average_price_nominal_euros/p0*100,
           pl_m2 = average_price_m2_nominal_euros/p0_m2*100)
}
```

The index for each commune and by country

```{r}
commune_level_data <- get_laspeyeres_index(commune_level_data)

country_level_data <- get_laspeyeres_index(country_level_data)
```


We are going to create a plot for 5 communes and compare the price evolution in the communes
to the national price evolution. Let’s first list the communes:

```{r}
communes <- c("Luxembourg",
              "Esch-sur-Alzette",
              "Mamer",
              "Schengen",
              "Wincrange")

```


Plot the price of communes

```{r}
make_plot <- function(commune){

  commune_data <- commune_level_data %>%
    filter(locality == commune)

  data_to_plot <- bind_rows(
    country_level_data,
    commune_data
  )

  ggplot(data_to_plot) +
    geom_line(aes(y = pl_m2,
                  x = year,
                  group = locality,
                  colour = locality))
}
```


Plot the house price data by commune

```{r, results='asis'}
res <- lapply(communes, function(x){
  
  knitr::knit_child(text = c(
    
    '\n',
    '## Plot for commune `r x`',
    '\n',
    '```{r, echo = FALSE}',
    'print(make_plot(x))',
    '```'
    
  ),
  envir = environment(),
  quiet = TRUE)
  
})

cat(unlist(res), sep="\n")
```

