data_doc.Rmd:
  path: dev/data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_save_data.Rmd:
  path: dev/flat_save_data.Rmd
  state: active
  R:
  - R/get_raw_data.R
  - R/get_laspeyeres_index.R
  tests:
  - tests/testthat/test-get_raw_data.R
  - tests/testthat/test-get_laspeyeres_index.R
  vignettes: vignettes/dev-save_data.Rmd
  inflate:
    flat_file: dev/flat_save_data.Rmd
    vignette_name: dev-save_data
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
