# WARNING - Generated by {fusen} from dev/flat_save_data.Rmd: do not edit by hand


# Basic unit tests of providing wrong dataset
testthat::test_that("Wrong data", {

  testthat::expect_error(
    get_laspeyeres_index(mtcars),
    regexp = "dataset must be one of"
  )

})

testthat::test_that("Empty data", {

  testthat::expect_error(
  # this subsetting results in an empty dataset
    get_laspeyeres_index(subset(mtcars, am == 2))
  )

})

# More complex unit tests checking that input = expected results of function
testthat::test_that("get_laspeyeres() produces correct results", {

  input_df <- expand.grid(
    list("year" = c(2010, 2011),
         "locality" = c("Bascharage", "Luxembourg"))
  )

  input_df$n_offers <- c(123, 101, 1230, 1010)
  input_df$average_price_nominal_euros <- c(234, 345, 560, 670)
  input_df$average_price_m2_nominal_euros <- c(23, 34, 56, 67)

  expected_df <- input_df

  # p0 should be always equal to the value in the first year
  expected_df$p0 <- c(234, 234, 560, 560)
  expected_df$p0_m2 <- c(23, 23, 56, 56)

  # pl should be equal to the price divided by p0
  expected_df$pl <- expected_df$average_price_nominal_euros / expected_df$p0 * 100
  expected_df$pl_m2 <- expected_df$average_price_m2_nominal_euros / expected_df$p0_m2 * 100

  # rename data to make assertion pass
  commune_level_data <- input_df

  testthat::expect_equivalent(
    expected_df, get_laspeyeres_index(commune_level_data)
  )

})


test_that("make_plot creates a ggplot object", {
  # Create sample data for testing
  country_data <- data.frame(
    locality = c("Country_A", "Country_A"),
    year = c(2010, 2011),
    pl_m2 = c(100, 120)
  )
  
  commune_data <- data.frame(
    locality = c("Commune_X", "Commune_X"),
    year = c(2010, 2011),
    pl_m2 = c(110, 130)
  )
  
  # Call the function with sample data
  plot <- make_plot(country_data, commune_data, "Commune_X")
  
  # Assert that the result is a ggplot object
  testthat::expect_true(ggplot2::is.ggplot(plot))
})


