# WARNING - Generated by {fusen} from dev/flat_save_data.Rmd: do not edit by hand

#' get_laspeyeres_index Calculates the Laspeyeres index for each commune with 2010 as the reference year
#'
#' @param dataset Flat data df as returned by clean_flat_data()
#' @param start_year Optional: Minimal year to consider. Defaults to 2009 because price data starts in 2010
#' @importFrom dplyr group_by ungroup mutate
#' @importFrom rlang quo
#' @importFrom tidyr fill
#' @importFrom rlang .data
#' @return The input dataset with added columns: p0, p0_m2, pl and pl_m2. p0 are prices at year 0 (2010), and pl are the index.
#' @export
#' @examples
#' \dontrun{
#' commune_level_data_laspeyeres <- get_laspeyeres(commune_level_data)
#' } 
get_laspeyeres_index <- function(dataset, start_year = "2010"){
  
  which_dataset <- deparse(substitute(dataset))
  
  group_var <- if(grepl("commune", which_dataset)){
               quo(.data$locality)
             } else {
               NULL
             }
  dataset |>
    group_by(!!group_var) |>
    mutate(p0 = ifelse(.data$year == start_year, .data$average_price_nominal_euros, NA)) |>
    fill(.data$p0, .direction = "down") |>
    mutate(p0_m2 = ifelse(.data$year == start_year, .data$average_price_m2_nominal_euros, 
  NA)) |>
    fill(.data$p0_m2, .direction = "down") |>
    ungroup() |>
    mutate(pl = .data$average_price_nominal_euros/.data$p0*100,
           pl_m2 = .data$average_price_m2_nominal_euros/.data$p0_m2*100)
}

#' make_plot Creates plot of Country and Commune Laspeyeres index prices (price adjusted) over time
#'
#' @param country_level_data The country level data frame.
#' @param commune_level_data The commune level data frame.
#' @param commune The commune to plot.
#' @importFrom dplyr filter bind_rows
#' @importFrom ggplot2 ggplot geom_line aes
#' @return A ggplot
#' @export
#' @examples
#' \dontrun{
#'commune_level_data_laspeyeres <- get_laspeyeres(commune_level_data)
#'make_plot(commune_level_data_laspeyeres, "Luxembourg")
#' }

make_plot <- function(country_level_data, commune_level_data, commune){

  commune_data <- commune_level_data |>
    filter(.data$locality == commune)

  data_to_plot <- bind_rows(
    country_level_data,
    commune_data
  )

  ggplot(data_to_plot) +
    geom_line(aes(y = .data$pl_m2,
                  x = .data$year,
                  group = .data$locality,
                  colour = .data$locality))
}
